services:
    postgresDb:
        image: postgres:16
        container_name: Todo
        environment:
            POSTGRES_DB: AppDb
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: Fleskeberg4
        ports:
          - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    
    api:
        build: 
          context: .
          dockerfile: Dockerfile
        container_name: api
        ports:
            - "8080:8080"
        environment:
            ConnectionStrings__DefaultConnection: "Host=postgresDb;Port=5432;Database=AppDb;Username=postgres;Password=${POSTGRES_PSW}"
            ASPNETCORE_URLS: http://+:8080
        depends_on:
            - postgresDb

volumes:
    postgres_data:
    



        
